name: firstWorkflows
on: [push]


jobs:
  first-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: print command
        run: echo "Hello World!"
      - name: print command
        run: |
          node -v
          npm -v
  second-action-job:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    steps:
      - name: printing string 
        run: Write-Output "Windows string"
      - name: Error Step
        run: doesnotexits